/* Hindi translations for the page interface. Proper names and source content stay intact. */
window.IP_SAKTI_HINDI = {
  "IP-SAKTI Sahayak · Ayurveda IP & regulatory guidance": "IP-SAKTI सहायक · आयुर्वेद में बौद्धिक संपदा और नियामकीय मार्गदर्शन",
  "Skip to main content": "मुख्य सामग्री पर जाएँ",
  "Smart India Hackathon 2026": "स्मार्ट इंडिया हैकाथॉन 2026",
  "Research prototype": "अनुसंधान प्रोटोटाइप",
  "Display preferences": "प्रदर्शन संबंधी प्राथमिकताएँ",
  "Use smaller text": "अक्षरों का आकार छोटा करें",
  "Use default text size": "अक्षरों का सामान्य आकार चुनें",
  "Use larger text": "अक्षरों का आकार बड़ा करें",
  "Use high contrast": "अधिक कंट्रास्ट चालू करें",
  "Use standard contrast": "सामान्य कंट्रास्ट चुनें",
  "IP-SAKTI Sahayak home": "IP-SAKTI सहायक का मुखपृष्ठ",
  "Sahayak": "सहायक",
  "IP-SAKTI Sahayak": "IP-SAKTI सहायक",
  "Ayurveda Intellectual Property & Regulatory Guidance": "आयुर्वेद में बौद्धिक संपदा और नियामकीय मार्गदर्शन",
  "KNOWLEDGE INTO PROTECTION": "ज्ञान से संरक्षण तक",
  "Main navigation": "मुख्य नेविगेशन",
  "Advisor": "सलाहकार",
  "Source library": "स्रोत संग्रह",
  "How it works": "यह कैसे काम करता है",
  "India & international frameworks": "भारत और अंतरराष्ट्रीय व्यवस्थाएँ",
  "FOR PRACTITIONERS, RESEARCHERS & INNOVATORS": "चिकित्सकों, शोधकर्ताओं और नवप्रवर्तकों के लिए",
  "Traditional knowledge.": "पारंपरिक ज्ञान।",
  "Informed innovation.": "समझ के साथ नवाचार।",
  "Navigate Ayurveda intellectual property and regulation with clear explanations, practical next steps, and sources you can verify.": "स्पष्ट व्याख्या, व्यावहारिक अगले कदम और जाँचने योग्य स्रोतों की मदद से आयुर्वेद में बौद्धिक संपदा और नियमों को समझें।",
  "Patents & trademarks": "पेटेंट और ट्रेडमार्क",
  "Traditional knowledge": "पारंपरिक ज्ञान",
  "Product regulation": "उत्पाद संबंधी नियम",
  "ROOTED IN TRADITION. GUIDED BY EVIDENCE.": "परंपरा से जुड़ाव। साक्ष्यों से मार्गदर्शन।",
  "Research guidance, not legal advice.": "यह शोध के लिए मार्गदर्शन है, कानूनी सलाह नहीं।",
  "Verify current law and consult a qualified professional before acting.": "कोई कदम उठाने से पहले मौजूदा कानून की पुष्टि करें और योग्य पेशेवर से सलाह लें।",
  "Connecting…": "कनेक्ट हो रहा है…",
  "YOUR RESEARCH DESK": "आपका शोध केंद्र",
  "From questions to clarity": "प्रश्नों से स्पष्ट समझ तक",
  "Ask a question directly": "सीधे प्रश्न पूछें",
  ", or start with your product details.": ", या अपने उत्पाद की जानकारी से शुरुआत करें।",
  "PRODUCT CLASSIFICATION": "उत्पाद का वर्गीकरण",
  "Know your formulation": "अपने फ़ॉर्मूलेशन को समझें",
  "Clear product details and start again": "उत्पाद की जानकारी हटाकर फिर से शुरू करें",
  "Reset": "रीसेट करें",
  "Find a preliminary": "अपने उत्पाद के लिए प्रारंभिक",
  "Indian regulatory route": "भारतीय नियामकीय प्रक्रिया",
  "based on your product’s intended use and confirmed facts.": "जानें—उसके अपेक्षित उपयोग और पुष्टि किए गए तथ्यों के आधार पर।",
  "Describe your product": "अपने उत्पाद का विवरण दें",
  "Optional": "वैकल्पिक",
  "What are you making, and how will it be used?": "आप क्या बना रहे हैं और इसका उपयोग कैसे होगा?",
  "For example: an Ayurvedic herbal cream intended to treat eczema.": "उदाहरण: एक्ज़िमा के उपचार के लिए बनाई गई आयुर्वेदिक हर्बल क्रीम।",
  "We’ll identify the intended use, then ask you to confirm the legal criteria. Keep confidential formula details out.": "हम अपेक्षित उपयोग पहचानेंगे, फिर आपसे कानूनी मानदंडों की पुष्टि करवाएँगे। फ़ॉर्मूले की गोपनीय जानकारी यहाँ न लिखें।",
  "Use description": "इस विवरण का उपयोग करें",
  "Loading the classification questions…": "वर्गीकरण के प्रश्न लोड हो रहे हैं…",
  "You can ask a question without this step. Classification supports research; it does not establish patentability or grant a licence.": "आप इस चरण के बिना भी प्रश्न पूछ सकते हैं। वर्गीकरण शोध में मदद करता है; इससे पेटेंट की पात्रता तय नहीं होती और न ही लाइसेंस मिलता है।",
  "IP & REGULATORY GUIDANCE": "बौद्धिक संपदा और नियामकीय मार्गदर्शन",
  "Ask the IP-SAKTI advisor": "IP-SAKTI सलाहकार से पूछें",
  "New chat": "नई बातचीत",
  "Legal jurisdiction": "कानूनी क्षेत्राधिकार",
  "India": "भारत",
  "International": "अंतरराष्ट्रीय",
  "India + international": "भारत + अंतरराष्ट्रीय",
  "Answer language": "उत्तर की भाषा",
  "English": "अंग्रेज़ी",
  "India · Ayurveda IP & regulation": "भारत · आयुर्वेद में बौद्धिक संपदा और नियम",
  "What would you like to understand?": "आप क्या समझना चाहते हैं?",
  "Explore patents, brands, biodiversity, traditional knowledge or product regulation.": "पेटेंट, ब्रांड, जैव विविधता, पारंपरिक ज्ञान या उत्पाद संबंधी नियमों के बारे में जानें।",
  "For example: Can a classical Ayurvedic formula be patented?": "उदाहरण: क्या शास्त्रीय आयुर्वेदिक फ़ॉर्मूले का पेटेंट कराया जा सकता है?",
  "Question text is not saved in the audit log.": "आपके प्रश्न का पाठ ऑडिट लॉग में सहेजा नहीं जाता।",
  "Get a sourced answer": "स्रोतों सहित उत्तर पाएँ",
  "Example questions": "उदाहरण के प्रश्न",
  "About answer languages & this chat": "उत्तर की भाषाओं और इस बातचीत के बारे में",
  "English source notes are always available.": "अंग्रेज़ी में स्रोत संबंधी टिप्पणियाँ हमेशा उपलब्ध हैं।",
  "Temporary chat: recent turns and product context; expires after 30 minutes of inactivity. Reloading starts a new chat.": "अस्थायी बातचीत: हाल के प्रश्न-उत्तर और उत्पाद का संदर्भ रखा जाता है; 30 मिनट तक कोई गतिविधि न होने पर यह समाप्त हो जाता है। पृष्ठ दोबारा लोड करने पर नई बातचीत शुरू होती है।",
  "Earlier questions and answers": "पिछले प्रश्न और उत्तर",
  "Your next step starts with a question": "आपका अगला कदम एक प्रश्न से शुरू होता है",
  "A clear, short answer first. Detailed reasoning and": "पहले स्पष्ट और संक्षिप्त उत्तर। ज़रूरत पड़ने पर विस्तृत तर्क और",
  "supporting sources whenever you need them.": "संबंधित स्रोत भी देखें।",
  "Source-linked answers": "स्रोतों के लिंक सहित उत्तर",
  "Clear evidence gaps": "साक्ष्यों की कमियों की स्पष्ट जानकारी",
  "A SIMPLE, SOURCE-LED PROCESS": "स्रोतों पर आधारित सरल प्रक्रिया",
  "How the advisor works": "सलाहकार कैसे काम करता है",
  "Build your context": "अपना संदर्भ तय करें",
  "Optionally classify your product. Select a jurisdiction and your preferred answer language.": "चाहें तो अपने उत्पाद का वर्गीकरण करें। क्षेत्राधिकार और उत्तर की पसंदीदा भाषा चुनें।",
  "Understand your options": "अपने विकल्प समझें",
  "Ask your question and get a short explanation. Follow up for a comparison or practical next steps.": "अपना प्रश्न पूछें और संक्षिप्त व्याख्या पाएँ। तुलना या व्यावहारिक अगले कदम जानने के लिए आगे प्रश्न पूछें।",
  "Check the evidence": "साक्ष्यों की जाँच करें",
  "Inspect source notes, dates and coverage gaps. Download your brief for professional review.": "स्रोत संबंधी टिप्पणियों, तारीखों और जानकारी की कमियों की जाँच करें। पेशेवर समीक्षा के लिए अपना संक्षिप्त विवरण डाउनलोड करें।",
  "THE EVIDENCE BEHIND THE ADVISOR": "सलाहकार के उत्तरों का साक्ष्य आधार",
  "The source library": "स्रोत संग्रह",
  "Curated sources for Ayurveda IP and regulatory research. Source dates are not live verification dates; this library is not an exhaustive legal database.": "आयुर्वेद में बौद्धिक संपदा और नियामकीय शोध के लिए चुने हुए स्रोत। स्रोतों की तारीखें उनकी वर्तमान स्थिति की पुष्टि नहीं करतीं; इस संग्रह में सभी कानूनी जानकारी शामिल नहीं है।",
  "Search sources": "स्रोत खोजें",
  "Statute, section, topic…": "अधिनियम, धारा, विषय…",
  "Jurisdiction": "क्षेत्राधिकार",
  "All jurisdictions": "सभी क्षेत्राधिकार",
  "Review status": "समीक्षा की स्थिति",
  "All sources": "सभी स्रोत",
  "Needs primary review": "प्राथमिक स्रोत की समीक्षा आवश्यक",
  "Time-sensitive": "समय के साथ बदल सकने वाली जानकारी",
  "Supporting informed decisions in Ayurveda innovation.": "आयुर्वेद में नवाचार के लिए सोच-समझकर निर्णय लेने में सहायता।",
  "SMART INDIA HACKATHON 2026": "स्मार्ट इंडिया हैकाथॉन 2026",
  "Team Vector Bytes": "टीम Vector Bytes",
  "Independent research prototype. Not an official government service.": "स्वतंत्र अनुसंधान प्रोटोटाइप। यह आधिकारिक सरकारी सेवा नहीं है।",
  "TKDL’s restricted database is not ingested.": "TKDL के सीमित पहुँच वाले डेटाबेस की सामग्री इसमें शामिल नहीं की गई है।",
  "Back to top ↑": "ऊपर जाएँ ↑",
  "EXTERNAL RESOURCE": "बाहरी संसाधन",
  "Close consent dialog": "सहमति का संवाद बंद करें",
  "Open a restricted-resource referral": "सीमित पहुँच वाले संसाधन का संदर्भ पृष्ठ खोलें",
  "We record your decision with an anonymous session identifier. Opening the public referral page does not unlock TKDL, purchase access or send an access request.": "हम आपके निर्णय को एक अनाम सत्र पहचानकर्ता के साथ दर्ज करते हैं। सार्वजनिक संदर्भ पृष्ठ खोलने से TKDL की पहुँच नहीं मिलती, पहुँच खरीदी नहीं जाती और न ही पहुँच का अनुरोध भेजा जाता है।",
  "Decline": "असहमत हूँ",
  "Agree & record": "सहमत हूँ, दर्ज करें",
  "Your consent was recorded.": "आपकी सहमति दर्ज कर ली गई है।",
  "Open official referral ↗": "आधिकारिक संदर्भ पृष्ठ खोलें ↗"
};
